# Generated by Django 4.1.4 on 2023-02-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
